### PR TITLE
Synced to latest version of ws2811 library

### PR DESCRIPTION
**Pull request by Gadgetoid**
I have synced your code to the latest version of the ws2811 library, required- I think- for support on the Pi 2 and Pi 3. It seems to work for me, and I humbly submit this PR for your approval.

Thanks for your efforts, by the way!

As a side-note, you may need to modify your `gamma-vs-direct.rb` example. The Unicorn HAT was never intended to run at full beans on a Pi ( full brightness, all white that is ), and will try to draw about 3x more power than the Pi is capable of supplying.

### CODE REVIEW

**Comment by Gadgetoid** [comment]
Update: I've added another commit to limit the brightness. This doesn't immediately reboot my Pi 3 + Touchscreen combo!

**Comment by LimeBlast** [comment]
@wejn is there any chance we can get this pulled in, and deployed to ruby gems please? I'm keen on doing stuff with this library. Thank you.

**Comment by wejn** [comment]
Daniel,

Sure thing! I'll be in front of a computer tonight. Will take care of it.

Sorry I kept you waiting; life sometimes gets in the way...

M.

**Comment by LimeBlast** [comment]
Sorry if I came across as ungrateful or impatient, I'm just excited to play with this :) Thank you so much.

**Comment by Gadgetoid** [comment]
>  Sorry I kept you waiting; life sometimes gets in the way...

Never a truer word spoke. See the ~3 year gap of brutal neglect in my WiringPi ports for a good example of this! D'oh.

**Comment by wejn** [comment]
@Gadgetoid Thanks for the PR. I actually have no trouble running the full brightness on my RPI B+ with the official "RPi Universal Power Supply" from Pimoroni. But I don't have RPi2/3 for testing, so I'm just taking your PR as authoritative source. :-)

@LimeBlast nah, it's all good. I was just trying to explain that I was super busy past two weeks and can't easily get to it. Now I'm finally siting in front of a computer... so it's going to happen in the next hour or so. :-)

**Comment by Gadgetoid** [comment]
@wejn you're very welcome, thanks for making this port in the first place! My setup involved a Pi 3,  official 7" Touchscreen _and_ an External SSD for good measure- all powered from the official 2A adapter. It's a worst-case scenario when it comes to power, and the full-bright HAT pushed it right over the edge. While this might not happen for most people, I prefer to er on the side of caution!

**Comment by wejn** [comment]
Oh, yeah, that's definitely a bit different in terms of power draw.

And I agree, better to err on the side of caution. :+1: 

Btw, I'd be more than happy to include any of your creations within examples folder (that goes for both of you, @Gadgetoid and @LimeBlast). I know the examples are mostly lacking; after all, I created this ruby clone in order to be able to easily prototype the digi clock. (which still needs to be finished in terms of features)

**Comment by LimeBlast** [comment]
I'd be happy to submit as pull request with an example or two - if it's of any interest, I have a [running cat](https://gist.github.com/LimeBlast/74db06b0123fa70ba6d2) (not sure how good my code is, but it works).

**Comment by wejn** [comment]
@LimeBlast incorporated in 0.0.6, thank you!

**Pull request merged**
